# Generated by Django 2.2.16 on 2021-09-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20210910_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите изображение для поста', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
